# Generated by Django 3.2.5 on 2021-07-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('ACTION', 'Action'), ('DRAMA', 'Drama')], max_length=6),
        ),
    ]
